name: Let's go
on:
    push:
        branches: [main, deploy]
        #paths:
        #    - 'src/**'
        #branches-ignore: [test]
        #paths-ignore: ['docs/**']
    pull_request:
        branches: [main]
    # schedule:
    #     - cron: '0 2 * * *'         ##### Cronjob
    # workflow_dispatch:              ####### to manually trigger from Gitlab UI
jobs:
    first_test:
        runs-on: self-hosted

        steps:
            - name: Action checkout
              uses: actions/checkout@v4

            - name: install python
              uses: ./.github/actions/setup-python-env
              with:
                python-version: '3.10'
                requirements-path: 'requirements.txt'

            - name: Get dependencies
              run: |
                python3 -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Lint with Flake8
              run: make lint

            - name: Run tests
              run: pytest --junitxml=tests/output/results.xml

            - name: upload test results
              if: success() && github.event_name == 'push'
              uses: actions/upload-artifact@v4
              with:
                name: test-results
                path: ./tests/output/

    second_test:
        runs-on: ubuntu-latest
        needs: first_test
        steps:
            - name: checkout code
              uses: actions/checkout@v4